### ISSUE TITLE
Function to check if a certain variable is present

### ISSUE THREAD

**Issue by johnnyontheweb** [adletec/sonic#32]
Hello,
I need a function to check if a variable is already present or not inside the dictionary of the calculation engine (e.g. isVarDefined(varName), returning 0 if varName has not been already defined or 1 otherwise). In this case I cannot add a user's function, just because the argument is not numeric but the name of the variable is required.
Is there a way to do this?

thanks in advance

**Comment by vlow** [comment]
Hi, I'm not sure if I'm understanding you correctly. There is no variable dictionary inside of the calculation engine (assuming you're talking about the `Evaluator`). Also, you can only add user's functions to the Evaluator _before_ you evaluate expressions.

Do I get this right? You want to get all variable names used in a string expression so you know which name you can use for your custom functions?

**Comment by johnnyontheweb** [comment]
Yes, exactly, but I have a list of formulas (let's say a script) to be given to the Evaluator. I divided such list into blocks, to be executed conditionally.
Hence, I need the function isVarDefined(varName) to let the script know if a variable has already been defined or not. And yes, getting the variable names passed into a function will allow me to implement this easily.

**Comment by vlow** [comment]
The easiest way would obviously be to check against the variables you're passing into the Evaluator. But assuming you don't know those, you could use the `TokenReader` to get the list of `Token`s in the expression. You're interested in all `Text` tokens. These contain all variable names, function names and constants.

Unfortunately, the way the `AstBuilder` differentiates between those three is by checking if the text token is either a registered function name, or a registered constant name, so there is no easy way to _only_ get variables.

If you want to check if a certain variable name is present, and you don't expect collisions with function or constant names, you're golden. You can just check if the variable names you're looking for are present in the list of Tokens.

If you want to check if a text token is a variable/constant name _or_ a function name, you would have to check if the text token is followed by a Token of the type `LeftBracket`. In that case you could filter out all functions and what remains is constant and variable names.

**Comment by johnnyontheweb** [comment]
Thanks for that, I'll try.
