### ISSUE TITLE
Duplicate Values in Case Insensitive Mode Result in Exception

### ISSUE THREAD

**Issue by johnnyontheweb** [adletec/sonic#41]
Hello,
I just want to share a small improvement I made in AstBuilder.cs, please see https://github.com/johnnyontheweb/sonic/commit/16db768805c52fee0dba1df25029382b23e20942

IDK if it is related to my script to have an empty stack, but I believe it is safer in this way.

Finally, I made some other corrections to let it work without errors with case INsensitivity, such as:
https://github.com/johnnyontheweb/sonic/commit/c9c669160d55a29ea5443bf96ada59efbbb6c9e8
https://github.com/johnnyontheweb/sonic/commit/368ab60c163fbb842434a44d6d9809b3fb7ef1d0

it's just to have your opinion, or to know if I'm missing something.
thanks in advance

**Comment by johnnyontheweb** [comment]
Thanks a lot for the reply and comments.

For the first issue, TryGetValue is not working as expected. I got a _variable not present_ error for example when:
context.Variables.ContainsKey("rebarid") is true

but

context.Variables.TryGetValue("rebarID", out result) is false.

For the other comments on case sentivity, I made such changes because I got "An item with the same key is already present" in _ConvertVariableNamesToLowerCase_  when I try to recalculate an existing variable. For instance:
`myVar=min(0.8*var2,myVar)`
In this case I get the mentioned error.

I'm following your advices and Iìm trying to revert my changes, but the ones above by now seems to be not possible.

**Comment by vlow** [comment]
> For the first issue, TryGetValue is not working as expected. I got a variable not present error for example when:
context.Variables.ContainsKey("rebarid") is true

> but

> context.Variables.TryGetValue("rebarID", out result) is false.

This is consistent with the changes you made to `EngineUtil`. Does this only happen in your fork or can you reproduce the same behaviour in upstream, too?

> `myVar=min(0.8*var2,myVar)`

You won't be able to evaluate something like that in _sonic_, since sonic doesn't do assignments. If you want to evaluate the expression, you need to hand the expression part (`min(0.8*var2,myVar)`) to the `Evaluator`. But you'll have to remove the `myVar=` part. This is not a bug, it's simply not what _sonic_ is designed to do.

You can think of _sonic_ as a calculator which supports templates. Meaning: Your expression is a template and you can exchange the variables with numeric values, but you'll neither be able to do assignments, nor solve equations.

**Comment by johnnyontheweb** [comment]
Hello,
I forgot to mention but, to report such results, I have reverted my changes first, see this branch https://github.com/johnnyontheweb/sonic/tree/modTemp. To be sure, I'll test also with original sonic repo as soon as I have some time, and I'll let you know.

Yes, I'm aware there's no assignation. In my case, all the variables obtained from previous line of the script are added to sonic variables to consider. The error in your version of _ConvertVariableNamesToLowerCase_ is not easy to examine, since I cannot see which variable is repeated unless I rewrite it with a cycle.

**Comment by johnnyontheweb** [comment]
I'm back with tests made on official 1.4.0. I can confirm both bugs, in particular:

1. I'm working with case insensitive stuff. However, the conversion of variables is made in ConvertVariableNamesToLowerCase and the code cannot handle repeated variables in dictionary. In my case, the problem is that I have VAR2=0.4  and var2=0.2 in variables (I'm still talking about min(0.8*var2,myVar) ).

![error_D_vs_d](https://github.com/adletec/sonic/assets/10365055/cc4e6ce2-8053-45f4-93f7-32e50ded1e90)

2. stack error still happens.

![stack_error_finalFrame](https://github.com/adletec/sonic/assets/10365055/6a014b46-d2ef-476a-979c-1e58bc05dd60)

The previous frame is:
![stack_frame_2](https://github.com/adletec/sonic/assets/10365055/e0e81750-111a-476a-abd3-7be5c8aab635)

but please note that operatorStack.count == 0.

**Comment by vlow** [comment]
> In my case, the problem is that I have VAR2=0.4 and var2=0.2 in variables

I see, but in that case, I still see an exception as correct behaviour. You'll handing two different values for the same variable name to a function which must return a consistent, case-insensitive lookup table. There is no way for the method to determine, which value should be returned for `var2` if you're ignoring case sensitivity. So throwing an exception is "works as expected."

Admittedly, this could be a domain specific exception, e.g. `DuplicateVariableDefinitionException` with some helpful information like the variable name. But I still see the actual behaviour and the Exception as correct in this case.

**Comment by vlow** [comment]
I created a separate issue for the empty result stack, since it gets increasingly hard to discuss two seemingly unrelated issues in the same ticket (#42). Let's keep this thread to the duplicate values in case-insensitive mode only.

**Comment by johnnyontheweb** [comment]
I perfectly understand, as I should have done a consistent check of the variable dictionary passed to sonic, but since I have very long scripts I'd rather prefer to mantain my version of ConvertVariableNamesToLowerCase  by now,
Thanks a lot for your support.
