### ISSUE TITLE
Result stack empty

### ISSUE THREAD

**Issue by vlow** [adletec/sonic#42]
@johnnyontheweb reported a `InvalidOperationException` due to an empty stack in `AstBuilder` (#41). Since the issue mixes two independent topics, this is a separate issue for the analysis of the empty stack.

![image](https://github.com/adletec/sonic/assets/3588976/51b96591-c067-47f0-aae1-8b0f12bc3006)

Previous frame:
![image](https://github.com/adletec/sonic/assets/3588976/d6cc80fd-eefa-43e1-b577-3bc7eae0379d)

**Comment by vlow** [comment]
@johnnyontheweb, can you please provide the expression you're using when this happens?

**Comment by johnnyontheweb** [comment]
Here you are:
`min(min(b,h)*if(CD==1.0,1/3,1/2),min(if(CD==1.0,125,175)/mmfact,dBL*if(CD==1.0,6,8)))`

thanks for your help.

**Comment by johnnyontheweb** [comment]
Yes, it works perfectly.
I just want to ask if there's other potential issues when coming from Jace (I remember that max and min in Jace were accepting a variable number of arguments) just to know how to conduct tests and how in deep.
thanks in advance

**Comment by vlow** [comment]
Great, I've just published a new release including the fix :)

> I just want to ask if there's other potential issues when coming from Jace (I remember that max and min in Jace were accepting a variable number of arguments) just to know how to conduct tests and how in deep.
thanks in advance

This is the same for _sonic_. `max` and `min` are dynamic functions which will take a variable number of arguments. This is also true for `avg`, `median` and `sum`. All other default functions are static functions which will always take the same number of arguments.

Take a look at `[Evaluator:RegisterDefaultFunctions()](https://github.com/adletec/sonic/blob/c186a2945a0d97c755c9030bf22060409d9a9bb1/Adletec.Sonic/Evaluator.cs#L182)` for details.

Merry Christmas 🎄

**Comment by johnnyontheweb** [comment]
@vlow thanks a lot, and Merry Christmas !
