### ISSUE TITLE
Possible to use variables with spaces?

### ISSUE THREAD

**Issue by EddyHaigh** [adletec/sonic#45]
Is it possible to have variables defined that have spaces in the name like `"a Bc"` that can used in an overall expression e.g.  `num = "a Bc" + 2;`?

**Comment by vlow** [comment]
Not at the moment, no. Legal variable names must only consist of regular letters (regex `[a-zA-Z]+`). Can you tell me more about your use case? Maybe we can realize it some other way.

**Comment by EddyHaigh** [comment]
When taking in data from various data sources e.g. CSV we arent able to reformat some of headings which may contain spaces. We've had a fork of JACE that allowed use to treat variable names with quotes but with JACE and our Fork not really being maintained it would be nice get Sonic plugged in.

**Comment by vlow** [comment]
I'll have a look at treating quoted strings as a single token. Maybe we can find a way which won't add measurable overhead to the token parser. No promises, though.

**Comment by vlow** [comment]
I've added the functionality on the [branch linked to this issue](https://github.com/adletec/sonic/tree/experiment/45-possible-to-use-variables-with-spaces).

You can use quoted symbol (and function) names by using single quotes (`'`) like that:

```csharp
var evaluator = Evaluator.CreateWithDefaults();

// use single quotes inside string
var expression = "2 + 'foo bar'";

// define variables, const, functions, etc. without single quotes
var variables =  new Dictionary<string, double> { { "foo bar", 3 } }

var result = evaluator.Evaluate(expression, variables);
```

This will allow you to use quoted and unquoted representation to refer to the same variables, constants, and functions. I.e.

```csharp
var expressionA = "'a' + b"

// and

var expressionB = "a + 'b'"

// are equivalent.
```

So if I understand your use-case correctly, you should be able to do something like this:

```csharp
var expression = $"1234 + '{csvHeaderName}'"
var variables = new Dictionary<string, double> { { csvHeaderName, correspondingValue } }
```

without adding quotes to your headers.

Would you mind giving the implementation on the branch a test drive with your data and report any issues back to this thread?

**Comment by EddyHaigh** [comment]
Going to get some testing in for the next couples days to make sure that all my requirements are covered but so far looking good.

**Comment by EddyHaigh** [comment]
@vlow is this feature still something that can be put into Sonic?
