### ISSUE TITLE
Question: support for Greek characters

### ISSUE THREAD

**Issue by johnnyontheweb** [adletec/sonic#53]
Hello,
I'm wondering if sonic could support Greek characters as part of expressions, like
`ρ_i+1`

If I try with it in the Demo App, I get:
```Error: Invalid token "?" detected at position 0.

Stacktrace:
   at Adletec.Sonic.Parsing.TokenReader.Read(String expression) in Adletec.Sonic\Parsing\TokenReader.cs:line 296
   at Adletec.Sonic.DemoApp.MainWindow.calculateButton_Click(Object sender, RoutedEventArgs e) in Adletec.Sonic.DemoApp\MainWindow.axaml.cs:line 50.`
```

I had a look on the source, and I found that 'IsPartOfTextToken' uses, as one could expect, ASCII characters. So my question is: is there a way to make sonic work with Greek characters and to avoid that any non-ASCII is traslated as "?" ? Maybe using unicode string (e.g. "\u03C1" is ρ).
I tried to change that function as follows:
```
        private bool IsPartOfTextToken(char character, bool isFirstCharacter)
        {
            return (character >= 'a' && character <= 'z') || 
                   (character >= 'A' && character <= 'Z') || 
                   (!isFirstCharacter && character >= '0' && character <= '9') || 
                   (!isFirstCharacter && character == '_') ||
                   (character >= 'α' && character <= 'ω') || (character >= 'Α' && character <= 'Ω');
        }
```
and it seems to be working properly, at least with simple expression.
Do you see any potential issue with that?

thanks in advance

**Comment by vlow** [comment]
Hi, from version 1.5.0 on, you can use arbitrary characters [if you put them in single quotes](https://github.com/adletec/sonic?tab=readme-ov-file#handling-spaces-and-special-characters) in your expression.

Example:

```csharp
// use single-quotes to allow for arbitrary unicode strings as variable names in expressions
var expression = "sin('α') + 'ω'";
Dictionary<string, double> variables = new Dictionary<string, double>();
variables.Add("α", 0); // no need for quotation outside, just refer to your variables as you usually would
variables.Add("ω", 3.4);
double result = engine.Evaluate(expression, variables);
```

**Comment by johnnyontheweb** [comment]
Thanks for your reply, but the proposed change would allow to use them without quotation - anyway, good to know, thanks!

**Comment by vlow** [comment]
Hi! You're right, and that's worth considering. However, there are also some downsides to extending the parser for additional character classes and some benefits from a technical and maintenance perspective of the quotation-method:

- Parsing ASCII is fast; adding new conditions to the parser logic will come with a performance penalty which is bad for users who parse a lot of expressions and evaluate them only once.
- If everything which is not ASCII is enclosed by ASCII single quotes (`'`) we can skip a lot of logic and just look for the closing quote;
- Quotation also works for spaces and even reserved characters, which makes things like `'result of a+b' + c` a valid expression. It's powerful, but also universal, which makes it _one_ additional condition which tackles your greek characters as well as anything else.
- It's pretty error proof. Handling Unicode directly sometimes introduces nasty edge-cases.

However - I see the benefit in being able to use Greek characters directly. They are universally used in Math and Physics and I'll think about adding direct support similar to what you proposed :)
